### ISSUE TITLE
Compability with new laravel's airlock feature

### ISSUE THREAD

**Issue by thanosalexander** [nuxt-community/laravel-echo#10]
Hi. i want to open this thread to find a solution into this implementation.

However i succefully got authentication , in echo i receive only 
```
{"message":"Unauthenticated."}
Client can not be authenticated, got HTTP status 401
```
even if i set `Broadcast::routes(['middleware' => ['auth:airlock']]);` as suggested in documentation https://laravel.com/docs/7.x/airlock#authorizing-private-broadcast-channels.

**Comment by radudiaconu0** [comment]
ohh.......i cant find in the whole internet how can i fix this
=(((

**Comment by baka298** [comment]
is there a solution for Airlock/Sanctum ?
