### ISSUE TITLE
this.$echo not exists

### ISSUE THREAD

**Issue by sergeevpasha** [nuxt-community/laravel-echo#11]
well, I did everything as insctructed, but everytime, I try to use` this.$echo.channel `It keep saying, that I am trying to call channel on `null`. I spent 6h tried to get what went wrong, but still no result. Maybe there is somthing missed in instruction?

**Comment by ricardogobbosouza** [comment]
Hi @sergeevpasha 
Could you show the snippets of your code?

**Comment by sergeevpasha** [comment]
hi, so it was a axios redirect bug, that influenced that all... Once fixed, echo was found successfully. [More info ](https://github.com/nuxt-community/auth-module/issues/437)
