### ISSUE TITLE
Using private channels

### ISSUE THREAD

**Issue by farazappy** [nuxt-community/laravel-echo#12]
Hey,

I couldn't find anything about using private channels, is it supported.

According to Laravel Docs, in Echo we can do something like :
`Echo.private('App.User.${userId}')
    .notification((notification) => {
        console.log(notification.type);
    });`

But when I use
`this.$echo.private...something similar`
It isn't subscribing to the Private Channel.

What am I missing here?

**Comment by ricardogobbosouza** [comment]
Hi @farazappy 
To use private channels, you need:

```js
export default {
  echo: {
    broadcaster: 'pusher',
    key: '48a97e3feef8c4e454bf',
    authModule: true // enable auth module,
    authEndpoint: 'endpoint' // https://laravel.com/docs/7.x/broadcasting#defining-authorization-routes
  }
}
```
