### ISSUE TITLE
app.$auth is undefined

### ISSUE THREAD

**Issue by ceronem** [nuxt-community/laravel-echo#2]
Hi guys, I'm trying to get this module working with the auth module, but unfortunatelly this doesn't work because in the file plugin.js@13 "app.$auth" is undefined and no auth header is returned.

This is my nuxt.config.js:
```javascript
...
  modules: [
...
    '@nuxtjs/auth'
...
  ],
buildModules: [
...
    '@nuxtjs/laravel-echo'
...
  ],
  echo: {
    authModule: true,
    connectOnLogin: true,
    disconnectOnLogout: true,
    broadcaster: 'socket.io',
    host: process.env.LARAVEL_ECHO_HOST
  },
...
```

**Comment by ricardogobbosouza** [comment]
Hi @ceronem,
Fixed on `v1.0.1`
