### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by ceronem** [nuxt-community/laravel-echo#3]
file: nuxt.config.js
```javascript
  echo: {
...
    broadcaster: 'socket.io',
...
  }
```

It causes a "window is not defined" error at ../.nuxt/echo.js

**Comment by ricardogobbosouza** [comment]
@ceronem thanks for reporting
Fixed on v1.0.2

**Comment by ceronem** [comment]
> @ceronem thanks for reporting
> Fixed on v1.0.2

you're welcome. Thanks for the fix
