### ISSUE TITLE
NuxtJs: Runtime public config (or runtime private config)

### ISSUE THREAD

**Issue by popovicidinu** [nuxt-community/laravel-echo#33]
Hi. 

I noticed this repo hasn't been updated in a while, and it could benefit from quite a lot of new features/enhancements. Are you planning to maintain this repo or what's the plan going forward? 

One issue that I'm facing right now, is trying to inject variables at runtime config (rather than build), in a NuxtJS installation with ssr: false and target: server. (especially the pusher key, e.g. key: process.env.PUSHER_APP_KEY)

Either I'm not doing something right, or, from the looks of it, this is not supported. 

Any hints would be really appreciated.

**Comment by ricardogobbosouza** [comment]
Hi @popovicidinu 
I'm updating now, sorry for the delay
See #42

**Comment by pisethx** [comment]
I tried it but does not work in production. 

In $echo.option.host, its still use the built time host.

**Comment by samturrell** [comment]
@ricardogobbosouza i can't seem to find this change in the source anymore? Any idea what happened?

**Comment by i-galetsky-gs-by** [comment]
https://github.com/nuxt-community/laravel-echo-module/pull/75
