### ISSUE TITLE
app.$auth.getToken is not a function  with  nuxt/auth  5

### ISSUE THREAD

**Issue by huebnermarketing** [nuxt-community/laravel-echo#40]
![image](https://user-images.githubusercontent.com/77531198/110315688-98c81600-802f-11eb-9ded-da716e1e0214.png)
![image](https://user-images.githubusercontent.com/77531198/110315791-c1e8a680-802f-11eb-8288-3a29619087e4.png)

**Comment by huebnermarketing** [comment]
Syntext to get token 

nuxt/auth 4  => **$auth.getToken('local')**
nuxt/auth 5 => **$auth.strategy.token.get()**

**Comment by melvin78** [comment]
Unfortunately its not yet compatible with nuxt auth next. Check the commits section and change your function name

**Comment by ahmedhegazee** [comment]
The solution is to change it in the node modules folder as @huebnermarketing said

**Comment by ricardogobbosouza** [comment]
Try alpha version `2.0.0-alpha.0`
